# fly.toml file generated for fly-hello-nodejs on 2022-05-16T15:48:11+01:00

app = "fly-hello-nodejs"


[env]
  NODE_ENV = "production"
  PORT = 8080

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25

  [[services.http_checks]]
    interval = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "2s"
